// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Community_Basic","status":true,"description":"Basic plugin for manipulating important parameters.","parameters":{"cacheLimit":"20","screenWidth":"816","screenHeight":"624","changeWindowWidthTo":"","changeWindowHeightTo":"","renderingMode":"auto","alwaysDash":"off"}},
{"name":"MadeWithMv","status":true,"description":"Show a Splash Screen \"Made with MV\" and/or a Custom Splash Screen before going to main screen.","parameters":{"Show Made With MV":"false","Made with MV Image":"MadeWithMv","Show Custom Splash":"true","Custom Image":"SideGroupLogo","Fade Out Time":"80","Fade In Time":"80","Wait Time":"120"}},
{"name":"AmmoSystem","status":true,"description":"An rudimentary ammo system","parameters":{"xxxxx      //name of a parameter you want the user to edit":"zzzzz    // set default value for the parameter"}},
{"name":"EscapeRemove","status":true,"description":"","parameters":{}}
];
